Update/2.0.0
lightspeeddevelopment/lsx-projects pull request #136
Opened 2023-02-20 08:19 UTC by krugazul

### Requirements

Please review this branch of LSX Projects. We would like to know if there are any issues with the folder structure or naming conventions, or any coding practices you disagree with.

### Description of the Changes

#### Removed
- Removed all the frontend functions injecting code, CSS classes etc to the frontend.
- Removed PHP Templates and all functions relating to the template management.
- Renamed the admin class to "setup" to be more accurate.
- Removed all custom fields
- Removed all vendor libraries.

#### Added / Refactored
- Block patters registered via our [class](https://github.com/lightspeeddevelopment/lsx-projects/blob/update/2.0.0/classes/class-block-patterns.php).
- A [Function](https://github.com/lightspeeddevelopment/lsx-projects/blob/update/2.0.0/classes/class-block-patterns.php#L282) to overwrite the query loop blocks args, in order to create a [related projects](https://github.com/lightspeeddevelopment/lsx-projects/blob/update/2.0.0/classes/class-block-patterns.php#L242) pattern

2023-02-20 08:19 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/lightspeeddevelopment/lsx-projects/inspections/18ed24a2-5dd0-4762-8a1f-b90755246efb) was created.

2023-02-20 16:05 UTC, fklein-lu requested changes
This is a large PR that should be broken up into different PRs. See https://docs.wpvip.com/how-tos/create-good-changesets/ for background.

The removal of CMB2 for example would be a single PR. Depending on the amount of changes one could have two PRs: first one to remove the custom code using CMB2, and then a second one to remove the plugin itself.

Same for the removal of the JS and CSS files of the libraries

For the block patterns, I'd recommend using the auto-registration through the `patterns/` directory, see https://wpdevelopment.courses/learn/building-block-themes/block-patterns-2/pattern-autoregistration/

As far as the structure is concerned, avoid using classes unless writing object oriented code. The code is procedural, but wrapped in a class. This brings no benefits.

2023-02-20 16:05 UTC, fklein-lu commented on classes/class-block-patterns.php
> +namespace lsx\projects\classes;
Any particular reasons why the namespaces are all lowercase, and not camelcase?

2023-02-20 16:05 UTC, fklein-lu commented on classes/class-block-patterns.php
> +	protected static $instance = null;
Singleton classes should be avoided, as they are difficult to test. If a singleton is needed, the retrieval of the singleton instance can be moved to a function.

2023-02-20 16:05 UTC, fklein-lu commented on classes/class-block-patterns.php
> +	private function __construct() {
Constructors should be side-effect free, and adding hooks is a side effect. Consider moving this to an `init()` method, or similar.

2023-02-20 16:05 UTC, fklein-lu commented on classes/class-block-patterns.php
> +			//'lsx-projects/featured-basic' => $this->featured_basic(),
Commented out code should be removed.

2023-02-20 16:05 UTC, fklein-lu commented on classes/class-block-patterns.php
> +			'description' => _x( '', 'Block pattern description', 'lsx-projects' ),
Description is missing.

2023-02-20 16:05 UTC, fklein-lu commented on classes/class-block-patterns.php
> +		if ( ! is_admin() && is_singular( 'project' ) && 'project' === $query['post_type'] && isset( $block->context['query']['related'] ) ) {
Early returns should be preferred over nested `if` statements.

2023-02-20 16:05 UTC, fklein-lu commented on classes/class-block-patterns.php
> +	 * @param array $query
Documentation should be complete. The fastest way to achieve this is to copy-paste the filter documentation from WordPress.

2023-02-20 16:05 UTC, fklein-lu commented on classes/class-block-patterns.php
> +	public function replace_related_vars( $query, $block, $page ) {
Consider adding type hints to the arguments, as well as include a typed return.

2023-02-20 16:05 UTC, fklein-lu commented on classes/class-block-patterns.php
> +			$query['orderby']      = 'rand';
Keep in mind that `rand` can be slow on large datasets.

2023-02-20 16:05 UTC, fklein-lu commented on classes/class-core.php
> +Core::get_instance();
Classes should not auto-instantiate on file inclusion. A file inclusion should be side effect free.

2023-02-20 16:05 UTC, fklein-lu commented on classes/class-frontend.php
> +			$class = sanitize_key( $matches[1] );
This assumes that `matches[1]` exists, but that won't be the case always. So first the value needs to be checked before it is acted on.

2023-02-20 16:05 UTC, fklein-lu commented on classes/class-frontend.php
> +	public function term_link_tags( $links ) {
This function should have a doc block explaining what it does.

2023-02-21 15:11 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/lightspeeddevelopment/lsx-projects/inspections/65879ad2-4a7b-4ce0-9cf7-31cca034ac0d) was created.

2023-02-24 12:52 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/lightspeeddevelopment/lsx-projects/inspections/0d3721fd-4115-4cf2-9729-8ecb521500f3) was created.

2023-02-24 13:02 UTC, krugazul commented on classes/class-block-patterns.php
> +namespace lsx\projects\classes;
Ive corrected the namespace - #137

2023-03-07 07:33 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/lightspeeddevelopment/lsx-projects/inspections/62d16fc2-c20a-4c74-988f-d9bdebc9983b) was created.

2023-04-04 11:59 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/lightspeeddevelopment/lsx-projects/inspections/b68549af-6e56-4029-b99d-031bea9722e1) was created.

2023-06-12 02:44 UTC, closed without merging